### ISSUE TITLE
Compiling rocThrust with a local test rocPRIM installation for target -1031?

### ISSUE THREAD

**Issue by klausbu** [ROCmSoftwarePlatform/rocThrust#268]
How can I specify the location of the rocPRIM installation or adapted sources to be used by rocThrust? 

The CMakeLists.txt option is to download and build rocPRIM but I need to use the version I built that supports my platform or the sources I modified to support my platform.

**Comment by Snektron** [comment]
Hi, rocThrust looks for rocPRIM using CMake's `find_package()` function, and the required CMake config files are provided when installing rocPRIM. This means that you can use the regular CMake option to override the search path, ie by setting `-DCMAKE_PREFIX_PATH=path/where/you/installed/rocprim` when configuring rocThrust. That path is the same path that you set when passing `-DCMAKE_INSTALL_PREFIX=path/where/you/installed/rocprim` when installing rocPRIM.

Note that if you have rocPRIM also installed from your system package manager, the HIP compiler may automatically prefer that. In order to override that, you can pass `-DCMAKE_NO_SYSTEM_FROM_IMPORTED=TRUE` when configuring rocThrust.
