### ISSUE TITLE
[Issue]: optional.h uses non-member function with `->` 

### ISSUE THREAD

**Issue by yxsamliu** [ROCmSoftwarePlatform/rocThrust#404]
### Problem Description

A recent clang change (https://github.com/llvm/llvm-project/pull/90152) revealed a bug in rocThrust develop branch

https://github.com/ROCm/rocThrust/blob/f3a28e43355b0f439fb99a2210bd497ca59c8003/thrust/optional.h#L2756

rocThrust/thrust/../thrust/optional.h:2756:11: error: no member named 'construct' in 'optional<type-parameter-0-0 &>'

In `this->construct`, the arrow operator cannot be overloaded, therefore it can only access its own member function. However, construct is not its member function, since `optional<T &>` does not define `construct`. Although `optional<T>` inherits `construct` from its base classes, its member `construct` is not inherited by `optional<T &>` since they do not have inherit relation.

Since  `optional<T &>` behaves like a delegate of its member `m_value`, my guess of intention of `this->construct` is to 
perform `m_value->construct`, i.e., using the overloaded arrow operator. To make the arrow operator taking effect, `(*this)->` can be used. Therefor, the fix is

```
(*this)->construct(std::forward<Args>(args)...);
```

### Operating System

Ubuntu 22.04

### CPU

any

### GPU

AMD Radeon Pro W7900

### ROCm Version

ROCm 6.1.0

**Comment by Snektron** [comment]
Hi, thanks for the detailed report. Upon further investigation we realized that the entire use of `construct()` doesn't really make sense in `optional<T&>::emplace()`, and that it should change the stored address instead. This issue is actually also present in upstream [CCCL](https://github.com/NVIDIA/cccl/blob/c910b166afd6fb90175df6c1f4aa792ed80a9214/thrust/thrust/optional.h#L2782), and so that is the proper place to fix it.

I will work with CCCL to get it resolved, after which we can cherry pick the same change onto rocThrust.

**Comment by yxsamliu** [comment]
Is it possible to add a quick workaround since rocThrust is part of our internal CI and this issue is blocking compiler promotion.

**Comment by Snektron** [comment]
Sure, I'll make a similar PR on rocThrust momentarily

**Comment by Snektron** [comment]
Upstream issue https://github.com/NVIDIA/cccl/issues/1706 and merge request https://github.com/NVIDIA/cccl/pull/1707
